### ISSUE TITLE
Failed to connect to Standalone V8 VM

### ISSUE THREAD

**Issue by haroldjiang** [Nodeclipse/nodeclipse-1#107]
when debug js file in eclipse,the ide prompt with "Failed to connect to Standalone V8 VM"

UPDATE:

[solution is](https://github.com/Nodeclipse/nodeclipse-1/issues/107#issuecomment-31509550)

 to run `node --debug-brk app.js` first.

**Comment by rajivkanaujia** [comment]
I still cannot get it to work
my js file is simple
`	var http = require("http");

	// create a http server that writes hello world
	http.createServer(function(request, response) {

		// Send the HTTP header 
		// HTTP Status: 200 : OK
		// Content Type: text/plain
		response.writeHead(200, {
			'Content-Type' : 'text/plain'
		});

		// Send the response body as "Hello World"
		response.end('Hello World\n');
	}).listen(8081);

	//Console will print the message
	console.log('Server running at http://127.0.0.1:8081/');
`
When I try to debug this as a Node Application, I get following at Eclipse Console

`
Debugger listening on ws://127.0.0.1:5858/b1bdf38d-c53a-472d-89f8-6819c5e4c8b1
For help see https://nodejs.org/en/docs/inspector
`
But then V8 fails. I am not sure where I need to make the changes.

`
Nodeclipse/chromedevtools failed to connect to Standalone V8 VM ( Check Help (F1) and Support http://www.nodeclipse.org/#support )
. Info:
Timed out waiting for handshake
`
I am using Node: v8.1.0 and Eclipse Version: Neon.3 Release (4.6.3) Build id: 20170314-1500

**Comment by bryanpham85** [comment]
Seem the issue has been solved somewhere, however I'm still facing this issue with Eclipse Oxygen + Nodeclipse. Constantly got this error message "Failed to connect to Standalone V8 VM
Timed out waiting for handshake"

Already set up Debug configuration with argument "--inspect-brk".

Any help much appreciate it!

**Comment by rajivkanaujia** [comment]
I guess the problem may be due to Nodeclipse being behind releases. I had switch to Visual Source Code + Docker for Mac, and I was able to debug the JS project. I hope Eclipse team fixes the issues soon.

**Comment by bryanpham85** [comment]
thanks for check up @rajivkanaujia . It looked inactive upgrade recent days from Nodeclipse. I tried with IntelliJ which worked after few minutes for set up.

**Comment by paulvi** [comment]
Closing this issue, create new for any questions and reference #107

**Comment by paulvi** [comment]
One such ticket is #220 

There are many reasons why this message can be seen, so raise detail issue.
