### ISSUE TITLE
`doctype 5` is deprecated, you must now use `doctype html`

### ISSUE THREAD

**Issue by ghost** [Nodeclipse/nodeclipse-1#121]
Hello,

Creating a brand new express / jade project in nodeclipse 0.1.0 then running it as a node application is raising the following error:

`doctype 5 is deprecated, you must now use doctype html`

Simple enough to solve by replacing "doctype 5" by "doctype html" in layout.jade: better forget about "doctype 5" for next releases, don't you think?

**Comment by paulvi** [comment]
closing as old
