### ISSUE TITLE
Bug 442049 - Eclipse 4.4 (JSDT) Attempting to copy from .js files in project, using ctrl+c or right-click menu, hangs/crashes JSDT in a big project

### ISSUE THREAD

**Issue by neatcode** [Nodeclipse/nodeclipse-1#159]
When I attempt to copy some of my source code using ctrl+c or the right-click menu "copy" command in any of the .js files in one of my Node.js projects, Nodeclipse hangs every time. It spins the CPU up to 100% and takes up all available memory.

I have a zip file you can unzip and import the project to replicate the issue here: http://www78.zippyshare.com/v/80482621/file.html (Use the orange "Download Now" button, the others are ads)

Just unzip the file to a directory and import it into your workspace, then try to copy source code out of any of the .js files in the project. For instance, server.js in the root directory exhibits the problem on my PC.

Note that this issue does not exist in some of my other Node.js projects. The project I'm working on here is the standard "mean.io" boilerplate, so many people are likely to encounter the same problem if they try out Nodeclipse as mean.io is quite popular. I HAVE tried regenerating the project file for the project using "nodeclipse -prepare" (after deleting the old project files) and that generated a new project which I reimported, however the issue still exists.

Do you know what's going on here?

---

Nodeclipse version (From the about box):

Enide Studio 2014 based on preview of Eclipse 4.4 M4 Luna

Version: 0.11
Build id: org.apache.maven.model.Build@7e6abaff

"Eclipse Standard/SDK"

---

C:\Enide\workspace\testmeanapp1>java -version
java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)

---

OS:
C:\Enide\workspace\testmeanapp1>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 8
OS Version:                6.2.9200 N/A Build 9200

(64bit Windows)

**Comment by paulvi** [comment]
@elvisvoer and all

I am going to disable JSDT by default because of this ant ES6 support #194

**Comment by paulvi** [comment]
I guess this have been fixed in Eclipse long time ago.

Closing as old.
