### ISSUE TITLE
Eclipse cannot import gradle built project or cannot convert project to using gradle

### ISSUE THREAD

**Issue by ghost** [Nodeclipse/nodeclipse-1#167]
Hello,

I use Eclipse 4.4 with 

Gradle IDE Pack 3.6.x, ~~0.17~~
Nodeclipse/Enide Gradle for Eclipse 0.17
Minimalist Gradle Editor 0.17

I have run into the following problems trying to import a gradle built android project into Eclipse and changing an android project in Eclipse to be built using Gradle:
1)
 File >>> Import >>> Existing Project into Workspace
 Right click on project just imported, click on Gradle, click on task quick launcher

The error message is:

org.eclipse.osgi.internal.framework.EquinoxConfiguration$1
Could not fetch model of type 'EclipseProject' using Gradle distribution 'http://services.gradle.org/distributions/gradle-1.12-all.zip'.

The above error message is produced whenever a Gradle related operation is attempted.

2)
 File >>> Import >>> Gradle project Click on Build Model

The error message is:

org.eclipse.osgi.internal.framework.EquinoxConfiguration$1
Could not fetch model of type 'EclipseProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.0-bin.zip'.

Please let me know if you need additional information.

Thank you,

Alex Donnini

**Comment by aaidan** [comment]
You're right, I was selecting the root of the project directory (like you would in Eclipse), not the main project's directory. After selecting it, I did get the specialized wizard. Thanks!   http://goo.gl/8aE6LK

**Comment by paulvi** [comment]
:+1:
