### ISSUE TITLE
Incompatible with Aptana products.

### ISSUE THREAD

**Issue by abdelouahabb** [Nodeclipse/nodeclipse-1#181]
hi,
it seems that the latest versions of `titanium studio` and `aptana studio` are incompatible with `nodeclipse`

http://stackoverflow.com/questions/26921297/nodeclipse-dont-work-on-titanium-or-aptana/26985559

![](http://i.stack.imgur.com/EsKNz.jpg)

**Comment by paulvi** [comment]
Could you please reference that ticket, and give update

**Comment by abdelouahabb** [comment]
hi @paulvi just updated Aptana, and still not working, got monjadb and emmet, but no nodeclipse
![sans titre](https://cloud.githubusercontent.com/assets/2527234/7240575/f635b6e6-e7a9-11e4-9ac9-06eb53a882e8.jpg)
I ended up by using EnideStudio long ago, it works there, and I use it for Python too.

**Comment by paulvi** [comment]
I have not seen/tried newer Aptana products for 3 years.

Please create new issue for current version.
