### ISSUE TITLE
Nodeclipse Tooltip

### ISSUE THREAD

**Issue by ABLsaurusRex** [Nodeclipse/nodeclipse-1#183]
Convenient is not spelled "convinient".

**Comment by paulvi** [comment]
Thanks.

Where exactly is this typo?

**Comment by ABLsaurusRex** [comment]
nodeclipse-1
<https://github.com/Nodeclipse/nodeclipse-1/tree/0e9857302dbaaea5bea1119375921de298c80cf5>
/org.nodeclipse.pluginslist.core
<https://github.com/Nodeclipse/nodeclipse-1/tree/0e9857302dbaaea5bea1119375921de298c80cf5/org.nodeclipse.pluginslist.core>
/*plugin.xml*

On Sun, Jan 11, 2015 at 9:36 PM, Paul Verest <notifications@github.com>
wrote:

> Thanks.
>
> Where exactly is this typo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Nodeclipse/nodeclipse-1/issues/183#issuecomment-69524670>
> .
>



-- 
Greg Higgins
PEG Manager

**Comment by paulvi** [comment]
That is not helping.

Could you give screenshot.

**Comment by paulvi** [comment]
OK that was tooltip of Nodeclipse plugin list icon

closing now
