### ISSUE TITLE
Problem installing nodeclipse - Unable to read repository at http://www.nodeclipse.org/updates/

### ISSUE THREAD

**Issue by skovenborg** [Nodeclipse/nodeclipse-1#184]
I have a problem installing nodeclipse on my Luna Service Pack 1 installation. I try to drag the 'install'-button for marketplace to my Eclipse Workspace either from 
http://marketplace.eclipse.org/content/nodeclipse or http://www.nodeclipse.org/updates/. The marketplace identifies all the correct plugins but when I press 'Confirm' it complains and says:
"Unable to read repository at http://www.nodeclipse.org/updates/"

**From the error log:**
```java
java.io.IOException: http://www.nodeclipse.org/updates/ is not a valid repository location.
	at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:102)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
	at org.eclipse.epp.internal.mpc.ui.operations.AbstractProvisioningOperation.addRepositories(AbstractProvisioningOperation.java:89)
	at org.eclipse.epp.internal.mpc.ui.operations.ProfileChangeOperationComputer.computeInstallableUnits(ProfileChangeOperationComputer.java:302)
	at org.eclipse.epp.internal.mpc.ui.operations.ProfileChangeOperationComputer.run(ProfileChangeOperationComputer.java:150)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
````

**My session data:**
eclipse.buildId=4.4.0.I20140606-1215
java.version=1.7.0_65
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product

**Comment by JerimeC** [comment]
I'm getting the same problem

**Comment by paulvi** [comment]
Thank you for reporting.

Is the problem still on?
I have 20+ Eclipse instances, but all of them have Nodeclipse installed, so I can't test installing all plugins at once. Also it may be network related.

Because Nodeclipse updates is actually composite repository,
I guess some of them, I suspect JSHint, may happen to be to slow.
Please open Progress View before installing to see current operations and pay attention to status bar.

The solution is try again and see. Please report if it fails again (other day).

There are also update site archives at https://sourceforge.net/projects/nodeclipse/files/

**Comment by paulvi** [comment]
Yep, first try to install from http://www.nodeclipse.org/updates/1/

**Comment by JerimeC** [comment]
Paul, I tried the following day and it worked. Thank you!

**Comment by skovenborg** [comment]
It works for me too. Tried both http://www.nodeclipse.org/updates/1/, http://www.nodeclipse.org/updates and marketplace and they all seems to work. I guess it may have been a one-day thing.

**Comment by paulvi** [comment]
Thank you for reporting

closing..

The installation is to be simplified, but so far I only can come with Enide Studio .zip download, 
but that move into area of testing all possible OSes,
while I am still on Windows

**Comment by krutipandya** [comment]
Hi, Can anyone help me with this error while I'm trying to install nodeeclipse plug in on Eclipse, Version: Mars Release (4.5.0) 

![capture](https://cloud.githubusercontent.com/assets/10962829/13941748/0fe462ca-efa8-11e5-903c-f646874ad82a.JPG)

**Comment by paulvi** [comment]
@krutipandya a new issue could be better

Can you see site at http://www.nodeclipse.org/ ?

What is exact reason for Unable to read repository?

**Comment by paulvi** [comment]
Right now site is not available

@krutipandya You can use update site `http://dl.bintray.com/nodeclipse/nodeclipse/1.0.2f/` while waiting for GitHub support

**Comment by s332401890** [comment]
http://dl.bintray.com/nodeclipse/nodeclipse/1.0.2f/ worked for me

**Comment by paulvi** [comment]
New issue should have worked better for many people https://github.com/Nodeclipse/nodeclipse-1/issues/207

**Comment by krutipandya** [comment]
Thank you Paul. I appreciate it.

On Fri, Mar 25, 2016 at 7:36 AM, Paul Verest <notifications@github.com>
wrote:

> New issue should have worked better for many people #207
> <https://github.com/Nodeclipse/nodeclipse-1/issues/207>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Nodeclipse/nodeclipse-1/issues/184#issuecomment-201315611>
>



-- 
Best,
Kruti Pandya
408-661-9929
<http://t.sidekickopen04.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg65jFyWW1qMvRq8qC9DdW8q5y9d56dM_Wd1XJ8-02?t=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fkrutipandya90&si=6571547007647744&pi=bb330d82-440e-4be9-ffb4-6cf82514c710>
