### ISSUE TITLE
Nodeclipse add incompatible shortcuts with french keyboard

### ISSUE THREAD

**Issue by lildadou** [Nodeclipse/nodeclipse-1#185]
It seems that Nodeclipse add some shortcuts, like Ctrl+Alt+[ jump to "previous edit point". This example is strongly incompatible with french keyboard : for typing [ character with a french keyboard, you must enter Ctrl+Alt+[ (Alt Gr+5 to be exact).

**Comment by paulvi** [comment]
Nodeclipse itself (as in this git repo) does not defines any such shortcuts.

Please press <kbd>Ctrl+Shift+L</kbd> to see and redefine all Eclipse shortcuts.

I guess it would be Eclipse IDE issue.
Please reference it from here.

**Comment by lildadou** [comment]
It's strange, this problem appear after I installed Nodeclipse. I will check the reproductibility.

**Comment by lildadou** [comment]
I cannot reproduce the bug... I suppose that the bug is into the keyboard-chair middleware ^^'
Sorry for the disturb.

**Comment by paulvi** [comment]
Sometimes the order of plugins installation matters. 
But it is still not known which one could use that combination.
