### ISSUE TITLE
Extract Minimalist Gradle Editor

### ISSUE THREAD

**Issue by msteiger** [Nodeclipse/nodeclipse-1#187]
I think that the Minimalist Gradle Editor is a very useful Eclipse plugin that deserves to live in a space of it's own rather than being in a subfolder within the nodeclipse project.

This would make it easier to use it as a stand-alone and also to contribute to this project (separate code base, issue tracking system, etc). What do you think?

**Comment by paulvi** [comment]
I am fine.

It has been here together with other plugin to make release simple.

What other place could be?

Now, how about Gradle-IDE itself? see https://github.com/spring-projects/eclipse-integration-gradle/commit/2c14b33cf947c0da241f158ef405898a3fa751e2

And what about Gradle-for-Eclipse http://www.nodeclipse.org/projects/gradle ?

**Comment by paulvi** [comment]
Extracting into new repo per se is sure not a problem.

**Comment by paulvi** [comment]
@kdvolder expressed as keeping two works separately.

**Comment by msteiger** [comment]
Sorry, what does that mean? Is @kdvolder going to extract this folder into a new project?

**Comment by kdvolder** [comment]
No, it means that I don't think we should move node-eclipse gradle editor into eclipse-integration gradle's github repo. But rather they should remain separate projects in terms of code base. Whether or not it becomes a separate project independent of node-eclipse is not really up to me. 

It sounds to me, however, that Paul thinks its a good idea, but I don't want to speak on his behalf. 

I don't have a connection to node-eclipse or its gradle editor. I am however happy if Paul continues to bundle his gradle editor with our spring Gradle tooling as a marketplace install, this makes good sense as they offer complementary functionality. That however doesn't require that we merge to two code-bases.

**Comment by paulvi** [comment]
Thanks to Kris for clarifying again.

Martin, I would say that I am to act as facilitator right now:  
I don't have time now (looking for job actually), but if someone would like to add a few features (or much more) I am here to help.

However I will not create a new repo when there's no one signed up to use it, as keeping many small plugins within one maven project simplifies release.

Would you like to do a change?

**Comment by msteiger** [comment]
Maybe it could become part of [gradle's buildship project](https://github.com/eclipse/buildship)? It aims to "provide a deep integration of Gradle into Eclipse".

A related discussion can be found in the gradle forums:
https://discuss.gradle.org/t/gradle-plugin-for-eclipse/8670/17

**Comment by paulvi** [comment]
That is new thing for me, thanks.

It seems like there are actually from Gradleware, see https://github.com/etiennestuder main committer.

I wonder if @kdvolder already knows. Inviting  @etiennestuder to comments as well.

P.S. Kris is already in that thread.

**Comment by etiennestuder** [comment]
Kris and I have been in touch on our Gradle forum. We will look into the Gradle Editor topic.

**Comment by paulvi** [comment]
@msteiger Martin, I am going to do this. Also to try gradle build for Eclipse plugins and OSGi as well.

**Comment by msteiger** [comment]
@paulvi great! Afaik, @etiennestuder and others are working on [BuildShip](http://projects.eclipse.org/projects/tools.buildship). Does it not include an editor for gradle files?

**Comment by etiennestuder** [comment]
@msteiger Our development efforts in Buildship currently focus on build users and not yet on build masters. Thus, providing editor support is on our list, but for later.

**Comment by msteiger** [comment]
Thanks for the clarification. Maybe I can help with the gradle editor, @paulvi - please let me know when/where you setup the code base.

**Comment by paulvi** [comment]
It is already in https://github.com/Nodeclipse/GradleEditor 
I need sometime to work on Build with Gradle https://github.com/Nodeclipse/GradleEditor/issues/1 (as don't know yet how), but any one can import `org.nodeclipse.enide.editors.gradle` project as Run as Eclipse Application.

I will rename to "Gradle Editor", but feature name stay the same, so users can update seamlessly.

Referencing @vogella who may be interested, ref #202 

and closing this issue.

Martin, let's continue conversation as issues on https://github.com/Nodeclipse/GradleEditor
