### ISSUE TITLE
PhantomJS Project in Eclipse (with Nodeclipse): NullPointerException when trying to run js file that is present in a folder

### ISSUE THREAD

**Issue by Manali-J** [Nodeclipse/nodeclipse-1#188]
Nodeclipse plugin version: Nodeclipse PhantomJS 0.17 (see screenshot nodeclipse 0.17)
Eclipse Version: Luna Service Release 1 (4.4.1)
Stackoverflow question: http://stackoverflow.com/questions/29457542/phantomjs-project-in-eclipse-with-nodeclipse-nullpointerexception-when-trying

Reproducible: Yes - consistently

Description:
After creating a PhantomJS Project, if we create a javascript file and place it in any folder created under the project and try to run the .js file, a NullPointerException is being thrown in Eclipse. Note that if we don't create any folder structure under the project and try to run the .js files, the scripts run fine. Basically, any attempt to run a script placed inside a folder gives an error. (see screenshot "Folder structure.png"). 

Steps:
1. Install Nodeclipse PhantomJS plugin 0.17 from the Eclipse marketplace
2. Launch Eclipse and click on File->New->PhantomJS Project
3. Give a name the project, enter other details and click on Finish
4. Under your PhantomJS project, create any folder
5. Right click on the folder created and select New->JavaScript file
6. Enter any piece of code in the .js file (Ex. console.log("Hello World");) and run the .js file.

Expected result:
Script should run without any errors

Actual result: 
User is getting a NullPointerException. (see screenshots Error1.png and Error2.png)

Exception details:

An internal error occurred during: "Launching PhantomJSTest-Test1.js".
java.lang.NullPointerException

Additional details:

java.lang.NullPointerException
	at org.nodeclipse.phantomjs.launch.LaunchConfigurationDelegate.launch(LaunchConfigurationDelegate.java:81)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

![nodeclipse 0 17](https://cloud.githubusercontent.com/assets/11750928/7044877/b0483ed0-de15-11e4-95f0-f1fec1c76c9c.PNG)
![error2](https://cloud.githubusercontent.com/assets/11750928/7044995/f4973e00-de16-11e4-818b-bd211cc9dd6b.PNG)
![nullpointerexception](https://cloud.githubusercontent.com/assets/11750928/7044997/f49fd8e4-de16-11e4-8b38-54e040b48f54.PNG)
![error1](https://cloud.githubusercontent.com/assets/11750928/7044996/f49c2d16-de16-11e4-98cc-6392e455f82f.PNG)
![folder structure](https://cloud.githubusercontent.com/assets/11750928/7045025/3527cb4c-de17-11e4-84c1-9cdabedd71a0.PNG)

**Comment by paulvi** [comment]
First, thank for the first feedback on PhantomJS plugin.

I have tried using Phantom 1.9.2 on Windows 7,
Nodeclipse:0.17.0.201409260953 Eclipse:4.4.0.v20140606-1215 Java:1.8.0_05 OS:win32,x86_64

And it worked well when launching from Project Explorer or from Editor

![pha](https://cloud.githubusercontent.com/assets/1614482/7085881/c7f53422-dfad-11e4-8d01-2d5c8e293ae4.PNG)

What is your path to phantom.exe ? Does it have spaces or other suspicious characters?

Mine is "D:\Progs\phantomjs-1.9.2-windows\phantomjs.exe"

**Comment by Little-Panda** [comment]
The path for me is D:\phantomjs.exe. Is there any important point I am missing? My phantomjs version 1.9.2.

**Comment by paulvi** [comment]
Well, "D:\phantomjs.exe" is not nice (root of drive D:), but it should work (like any)

I have looked at [source org.nodeclipse.phantomjs.launch.LaunchConfigurationDelegate.launch(LaunchConfigurationDelegate.java:81)](https://github.com/Nodeclipse/nodeclipse-1/blob/master/org.nodeclipse.phantomjs/src/org/nodeclipse/phantomjs/launch/LaunchConfigurationDelegate.java#L81)

it is 

`String filePath = ResourcesPlugin.getWorkspace().getRoot().findMember(file).getLocation().toOSString();`

What is special about our js file?

**Comment by Little-Panda** [comment]
Actually I've tried two paths - "D:\MANALI\phantomjs-1.9.2-windows\phantomjs-1.9.2-windows" and  "D:\phantomjs.exe". Issue happens after I create a folder.

The js file had this script which works fine when I don't create a folder - 

var page = require('webpage').create();
page.open('http://example.com', function(status) {
  console.log("Status: " + status);
  if(status === "success") {
    page.render('example.png');
  }
  phantom.exit();
});

Should I consider doing a fresh install of Eclipse & Nodeclipse?

**Comment by paulvi** [comment]
The Phantom path  is path to Phantom executable, so it should have .exe in the end.

Fresh install of Eclipse & Nodeclipse would make no difference.

Try debug yourself https://github.com/Nodeclipse/nodeclipse-1/tree/master/org.nodeclipse.phantomjs

or guess what is wrong with `String filePath = ResourcesPlugin.getWorkspace().getRoot().findMember(file).getLocation().toOSString();`
line. I ran out of ideas.

**Comment by paulvi** [comment]
What is .js file path?
What is Project path?

**Comment by Little-Panda** [comment]
.js path - "D:\MANALI\WORKSPACE\PhantomJSTest\test\Test1.js"
Project path - D:\MANALI\WORKSPACE\PhantomJSTest

**Comment by Little-Panda** [comment]
I think this is the thing causing the problem. I tried the Link to Existing folder option but that did not help:

![capture](https://cloud.githubusercontent.com/assets/11750928/7087154/c3335d18-dfa5-11e4-8ffc-aa3a4f9d02fc.PNG)

**Comment by paulvi** [comment]
Tried again with Eclipse 4.4.2
all works fine.

**Comment by Little-Panda** [comment]
I have followed all the instructions from this [link](http://www.nodeclipse.org/updates/). 

This is what is causing the issue (below screenshot).  I have tried copying the node_modules to the project but that did not help and I'm not sure which environment variable has to be set. I'm still looking.

![image](https://cloud.githubusercontent.com/assets/11750928/7119501/a22f8562-e223-11e4-8ef1-0c9e0fcfd691.png)

**Comment by paulvi** [comment]
Well, from "Eclipse Installation Detail" it seems that you have not installed Nodeclipse Nodejs Feature Set. I have never had Eclipse yet with PhantomJS, but without Nodejs...

Also you have also a lot of stuff like C++, Python... Maybe it may cause.
So yes please try one more clean Eclipse instance or Enide Studio.

**Comment by Manali-J** [comment]
I don't know what the problem was with installing the Nodeclipse plugin. So, I downloaded the Enide Studio and I am not facing any issues with Enide Studio.

For a PhantomJS Project, I needed only the following two things:

1. Enide Studio 2014
2. PhantomJS 

Thank you for being so patient.
