### ISSUE TITLE
Minimalist Gradle editor does not work with Eclipse 4.6

### ISSUE THREAD

**Issue by vogella** [Nodeclipse/nodeclipse-1#202]
Would be nice if you also allow Eclipse 4.6

**Comment by paulvi** [comment]
Thank you for raising, I will try Eclipse N this or next month

**Comment by paulvi** [comment]
works for me

![2222](https://cloud.githubusercontent.com/assets/1614482/11608769/df47b944-9bad-11e5-8d53-8514b5e87e29.PNG)

**Comment by paulvi** [comment]
Please provide stacktrace or screenshot of a problem

**Comment by neilw1** [comment]
I'm running latest version of Eclipse (Mars - 4.5.2) and I can see the properties window for the plugin but absolutely nothing happens in the editor, it's just black and white, uncommented. Am I supposed to have any other plugins installed? i do not have nodeclipse. All I want is the facilities of minimalistic gradle editor, nothing more.

**Comment by paulvi** [comment]
@neilw1 
Right-click in Project Explorer - Open with Minimalist Gradle Editor, check you got coloring.
