### ISSUE TITLE
When debugging, any console logging that outputs an object is terminating the debugger.

### ISSUE THREAD

**Issue by JeffML** [Nodeclipse/nodeclipse-1#206]
Example:

```
var obj = {"an": "object"};
console.log("this will fail", obj);
```
stack trace:

> eclipse.buildId=4.5.1.M20150904-0015
> java.version=1.8.0_73
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
> Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
> Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -data file:/C:/Users/Jeff/workspace_trid/ -product org.eclipse.epp.package.jee.product
> 
> org.chromium.debug.core
> Info
> Sat Feb 13 11:49:26 PST 2016
> SDK:org.chromium.sdk.internal.transport.SocketConnection: Shutdown requested
> 
> java.net.SocketException: Connection reset
>     at java.net.SocketInputStream.read(Unknown Source)
>     at java.net.SocketInputStream.read(Unknown Source)
>     at java.net.SocketInputStream.read(Unknown Source)
>     at org.chromium.sdk.internal.transport.LineReader.readLine(LineReader.java:88)
>     at org.chromium.sdk.internal.transport.Message.fromBufferedReader(Message.java:134)
>     at org.chromium.sdk.internal.transport.SocketConnection$ReaderThread.run(SocketConnection.java:166)

JSON.stringify of an object will also crash the debugger.

I have tried to use Enide 2015 from http://sourceforge.net/projects/nodeclipse/files/.

I downloaded Enide 2015 and opened my existing Mars workspace. Loaded fine, but when debugging it still terminates on console dumps of objects. 
  	 	
Let me know if there is anything further I can provide.

**Comment by paulvi** [comment]
It is the same as on http://stackoverflow.com/questions/35384729/nodeclipse-crashing-when-debugging-mars-jdk-8-win10 , isn't it?

**Comment by JeffML** [comment]
Yes.

**Comment by paulvi** [comment]
Please create an issue at https://github.com/nodejs/node/issues/new (and reference this one)
it requires now to provide some version information, though I think I had similar issue long ago.

As it is `SocketException: Connection reset`, it is node site initiated, so I bet it is node issue, so let's check

**Comment by JeffML** [comment]
It was a nodejs bug.  See referenced ticket.

**Comment by paulvi** [comment]
Really thank you, Jeff, for solving and sharing.

So one just need v4.3.1+ version
