### ISSUE TITLE
Error while Updating

### ISSUE THREAD

**Issue by KunalGautam** [Nodeclipse/nodeclipse-1#207]
It seems that www.nodeclipse.org is showing blank page. Eclipse is Unable to read repository at http://www.nodeclipse.org/updates/.

**Comment by ying1** [comment]
Having the same issue here.

**Comment by ryzhman** [comment]
+1 - The same problem of "Unable to read repository"

**Comment by paulvi** [comment]
Thank you for reporting. I was 3 days at trainings without computer, so resolution was slow.

There issue is solved, please see https://github.com/Nodeclipse/www.nodeclipse.org/issues/72 and http://www.nodeclipse.org/#news

**Comment by paulvi** [comment]
Guys, please read and remember http://www.nodeclipse.org/updates/ page for offline installation from

https://sourceforge.net/projects/nodeclipse
