### ISSUE TITLE
Nodeclipse's CPU utilization is very high

### ISSUE THREAD

**Issue by qianzhangxa** [Nodeclipse/nodeclipse-1#213]
I am using Mac (10.10.5) and I already have Eclipse Mars (4.5.2) installed. Now I installed Nodeclipse 1.0.2 with Eclipse Marketplace and created a Nodejs project (reactjs), and then I found the CPU utilization of Eclipse is very high (over 100%).

Can anyone let me know how to fix it? Thanks!!!

**Comment by paulvi** [comment]
Anyone can answer on http://stackoverflow.com/questions/38438369/nodeclipses-cpu-utilization-is-very-high Here it is likely only me.

Read the answer on SO and give your steps, screenshot. So that it would be possible to reproduce on other Mac.

**Comment by paulvi** [comment]
This should have been Eclipse issue, possibly JSDT.
