### ISSUE TITLE
Problem npm install nodeclipse in Linux / Ubuntu

### ISSUE THREAD

**Issue by mparanhos** [Nodeclipse/nodeclipse-1#214]
I have nodejs and npm installed.
I tested `npm -v` and `nodejs -v` it worked, showed the current version.

1. I used the `nodeclipse -p` command line in my empty folder to create the project structure, but I received the error: command not found.

2. I uninstalled the nodeclipse with `npm uninstall` and installed again with `sudo npm install` and did not work.

3. I used the root account and run the `npm install` also did not work.

I don´t found the npm or nodejs references to set the environment variable to set the nodeclipse.

Can anyone help please?

**Comment by mparanhos** [comment]
I used the nodeclipse -p command line in my empty folder to create the project structure, but I received the error: command not found.

```
paranhos@pc-principal:~/workspace-javascript/react-sample$ nodeclipse -p
/usr/bin/env: "node": File or directory not found
```

**Solution:** _Create a Symbolic Link_
`sudo ln -s "$ (which nodejs)" /usr/bin/node`
or
`sudo ln -s /usr/bin/nodejs /usr/bin/node`

**Bug Report:** nodeclipse find node command but not nodejs command. Node.js for Linux use `nodejs` as command and Windows uses `node` as command.

**Comment by paulvi** [comment]
also on http://stackoverflow.com/questions/38531239/nodeclipse-command-not-found-on-linux-after-install-it

I don't think this is bug of nodeclipse or node, as it is OS specific problem. (Because there was other package on Linux named `node`)

By the way, sources are in .js files here https://github.com/Nodeclipse/nodeclipse-1/tree/master/org.nodeclipse.ui/templates#nodeclipse-cli--installer

**Comment by mparanhos** [comment]
Thank @paulvi.
I also can solve this question, installing the new nodejs version for my linux distro.
Getting ".deb" package directly and following the instructions in the url´s: 

https://nodejs.org/en/download/package-manager/
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

In the version 4.4.7 was Included "node" and "nodejs" as command.
