### ISSUE TITLE
Eclipse MarketPlace install failure.

### ISSUE THREAD

**Issue by wayn23** [Nodeclipse/nodeclipse-1#217]
Running Eclipse Neon and browse market place and select Nodeclipse 1.0.2. Use all the default install options.

Install gets to 49% then throws exception
!MESSAGE Unable to read repository at http://github.eclipsesource.com/jshint-eclipse/updates/jshint-eclipse-0.10.1.20160216-0911-a8eac20/plugins/com.eclipsesource.jshint.source_0.10.1.20160216-0911.jar.

**Comment by paulvi** [comment]
That is network related issue. Try again later, or check http://www.nodeclipse.org/updates/ for other, e.g. offline options. 

Also you may unselect jshint-eclipse, as that is the one that causes issue.

Thanks for raising, please update on resolution.

**Comment by wayn23** [comment]
You are right.  I had tried it about 5 times over yesterday and today and it always hung at that spot. Didn't think it was a network problem as it was always the same exact message. This time it worked!
