### ISSUE TITLE
PATH is incorrect

### ISSUE THREAD

**Issue by ysstech** [Nodeclipse/nodeclipse-1#218]
logs print on the Console:
`
Nodeclipse:1.0.2.201509250223 Eclipse:4.4.2.v20150204-1700 Java:1.8.0_60 OS:macosx,x86_64
visit http://www.nodeclipse.org/

These environment variables will be applied automatically to every node launch.
APPDATA=
PATH=/usr/bin:/bin:/usr/sbin:/sbin
TEMP=
TMP=
SystemDrive=
`
PATH is incorrect。My Enviorment Node Path location at /usr/locale/bin。
How to fix it?

**Comment by paulvi** [comment]
http://www.nodeclipse.org/#support
