### ISSUE TITLE
Please provide a way to disable the nodeclipse console in Eclipse

### ISSUE THREAD

**Issue by wnm3** [Nodeclipse/nodeclipse-1#219]
With the extra console it is sometimes difficult to toggle between application consoles because it becomes part of the rotation (clicking on the console icon). More information is in stackoverflow here: http://stackoverflow.com/questions/41533122/remove-nodeclipse-console-from-console-view

Thank you.

**Comment by paulvi** [comment]
Have you already disabled Nodeclipse console usage in Preferences? So it will not appear on top for diagnostic messages?

**Comment by wnm3** [comment]
Yes. Will close.
