### ISSUE TITLE
can not visit www.nodeclipse.org website or install

### ISSUE THREAD

**Issue by XenoAmess** [Nodeclipse/nodeclipse-1#221]
http://www.nodeclipse.org/
it is not usable for me.
Also I cannot install or update nodeclipse(due to the same reason)
please make sure your website is still usable.

**Comment by auriusbendikas** [comment]
I have noticed that too. Then I have checked the activity of the plugin. Has not been any new commits for a year. I assume the project is not maintained. Currently looking for other plugins to do the job.

**Comment by paulvi** [comment]
I cannot open http://www.nodeclipse.org/ too. It redirects to http://127.0.0.1/
The domain fee for nodeclipse.org has been payed by @lamb , the initial creator (versions 0.1.x)
(we had similar issue maybe 2-3 years ago)
I will contact by all means to reach @lamb 

@auriusbendikas The project is maintained, but no more personal time is invested.
One of reasons I am not using Node.js for couple years now.

3 major authors are listed at https://github.com/Nodeclipse/www.nodeclipse.org/blob/gh-pages/index.html#L133

Yes, it is not possible to install as usual, bu only via direct p2 URL  
`http://dl.bintray.com/nodeclipse/nodeclipse/1.0.2f/`  
that changes with new versions.

**Comment by paulvi** [comment]
```
ping nodeclipse.org

Pinging nodeclipse.org [103.232.215.142] with 32 bytes of data:
Reply from 103.232.215.142: bytes=32 time=244ms TTL=52
Reply from 103.232.215.142: bytes=32 time=287ms TTL=52
Reply from 103.232.215.142: bytes=32 time=192ms TTL=52
Reply from 103.232.215.142: bytes=32 time=217ms TTL=52

Ping statistics for 103.232.215.142:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 192ms, Maximum = 287ms, Average = 235ms
```

**Comment by paulvi** [comment]
@lamb, It is more than just Nodeclipse users affected as for 3-4 years of my open source work, all updates were published www.nodeclipse.org, including
- Gradle IDE Pack
- Markdown Editor by Daniel @winterstein https://github.com/winterstein/Eclipse-Markdown-Editor-Plugin
- CSV Edit
and others, see subfolders under of `updates` :
https://github.com/Nodeclipse/www.nodeclipse.org/tree/gh-pages/updates

As of now, nodeclipse.org redirects to http://835.dopa.com/?dm=nodeclipse.org&acc=96F52E2F-2CB3-468B-900C-1A4B76552CAB&poprequest=1
So have someone overtaken the domain? There is so record in Chinese "您的域名已经到期，请联系您的服务商续费", that is "domain name expired, contact your service company".

Migrating users to new URL will be a bit painful, and actually not have time, as in the middle of rush project at work.

**Comment by paulvi** [comment]
spent 2-3 hours moving things to https://nodeclipse.github.io/

**Comment by lamb** [comment]
fix it

**Comment by paulvi** [comment]
I still cannot open, redirects to 127.0.0.1

**Comment by paulvi** [comment]
https://www.nodeclipse.org/ opens OK now.  
Closing the issue, but the plan is to migrate to https://nodeclipse.github.io/

**Comment by paulvi** [comment]
Happened again in 2019, raised as https://github.com/Nodeclipse/nodeclipse.github.io/issues/1
