### ISSUE TITLE
Gradle-IDE Pack Eclipse Marketplace Fails

### ISSUE THREAD

**Issue by kpb177** [Nodeclipse/nodeclipse-1#223]
When attempting to install Gradle IDE Pack 3.8x+1.0x with Eclipse Neon marketplace, I get the following error:
![image](https://user-images.githubusercontent.com/37883481/38055706-7e4dae84-32a8-11e8-88bf-32bacab1196b.png)

I saw some recent issues for moving over the URL, but the content.xml page it's complaining about gives me a 404 error.

**Comment by paulvi** [comment]
OK, thanks

that is continuation of #221

**Comment by kpb177** [comment]
Any progress on this error? Is there an alternative to manually install the plugin in the meantime?

**Comment by paulvi** [comment]
Should be OK now.

Changing update URL back to `http://nodeclipse.org/updates/gradle-ide-pack/` (as nodeclipse.org is OK now), I noticed, that https URL`https://nodeclipse.github.io/updates/gradle-ide-pack/` was used for Oxygen only. So users of older Eclipse should have been able to install via the entry, when nodeclipse.org got DNS resolution back.

**Comment by kpb177** [comment]
I get a new error (using Eclipse Neon):

```
HTTP Server 'Service Unavailable': http://nodeclipse.org/updates/gradle-ide-pack/content.xml
HttpComponents connection error response code 503.
```

I also can't hit http://nodeclipse.org/updates/gradle-ide-pack/ in my browser, but if I drop the gradle-ide-pack it works.

**Comment by paulvi** [comment]
Both http://www.nodeclipse.org/updates/gradle-ide-pack/ and http://nodeclipse.github.io/updates/gradle-ide-pack/ (without s) should work, if GitHub pages are available

**Comment by kpb177** [comment]
The URL Eclipse seems to be using is missing www, could that be the issue? 
![image](https://user-images.githubusercontent.com/37883481/39185639-e0cb86ce-4795-11e8-9e8c-8672a0cfe81f.png)

Also, when trying to hit that URL with the xml file Eclipse is looking for, that gives a 404 error, not sure if this is a problem either.
http://www.nodeclipse.org/updates/gradle-ide-pack/content.xml

**Comment by paulvi** [comment]
www.nodeclipse.org and nodeclipse.org should resolve to the same IP address

There are no `content.xml` but `compositeContent.xml`
https://github.com/Nodeclipse/www.nodeclipse.org/tree/gh-pages/updates/gradle-ide-pack,
so Eclipse just cannot acceess. (The screenshot looks like general network related issue, that would have been at time when nodeclipse.org was resolved not to GitHub pages)

You can directly use update site from this composite repository,
see https://github.com/Nodeclipse/www.nodeclipse.org/blob/gh-pages/updates/gradle-ide-pack/compositeContent.xml e.g.

`http://dist.springsource.com/release/TOOLS/gradle/`



From browser you can try https://nodeclipse.github.io/updates/gradle-ide-pack/compositeContent.xml
and https://nodeclipse.github.io/updates/gradle-ide-pack/compositeArtifacts.xml

And tell, what exact URL is  currently within your Eclipse -> Preferences -> Install/Update -> Available Software Site ?

**Comment by paulvi** [comment]
With one more report, checked that for Eclipse Install  
`http://nodeclipse.org/updates/gradle-ide-pack/` fails,  
`http://www.nodeclipse.org/updates/gradle-ide-pack/` is OK  
(while within a browser nodeclipse.org/updates/gradle-ide-pack/ will redirect to www. )

The problematic link was for older Eclipse versions
![image](https://user-images.githubusercontent.com/1614482/39281628-3f00335e-4938-11e8-8b6b-fd6648872b75.png)


Now https://marketplace.eclipse.org/content/gradle-ide-pack is updated to use only 
`http://www.nodeclipse.org/updates/gradle-ide-pack/` that is OK

**Comment by paulvi** [comment]
BTW both HTTPS and HTTP github.io URLs (
`https://nodeclipse.github.io/updates/gradle-ide-pack/` and `https://nodeclipse.github.io/updates/gradle-ide-pack/` )
work in my Eclipse Oxygen.3 / STS 3.9.3

So maybe there are problems with HTTPS support in older Eclipse versions.
@kpb177 What Eclipse version are you using?

**Comment by kpb177** [comment]
I'm using Eclipse Neon.3, I just tried it and the install worked, but I didn't change any settings. So I guess something you did fixed it. 
Thanks!

**Comment by paulvi** [comment]
The URL was updated for Eclipse Neon and older.

Happy coding!

**Comment by calcasmy** [comment]
Hello Paulvi, The issues seems to be reoccurring while trying to install the plug in.  can you please help... Please find the attached image below.

Eclipse Version: Neon.
Gradle Plugin: Gradle IDE Pack 3.8.x+1.0.x

![image](https://user-images.githubusercontent.com/19392146/54926831-7a6ebb80-4ee7-11e9-9ac8-ed2957e5ca8c.png)

**Comment by paulvi** [comment]
See https://github.com/Nodeclipse/nodeclipse.github.io/issues/1

**Comment by paulvi** [comment]
OK

https://marketplace.eclipse.org/content/gradle-ide-pack 

is updated to use 

https://nodeclipse.github.io/updates/gradle-ide-pack/

Thank for telling,  
but new issues would be better.

**Comment by calcasmy** [comment]
Thank you for the quick response Paul. Sure, Will keep in mind to create new issue in the future.
