### ISSUE TITLE
Gradle-IDE Pack 3.8.x+1.0x Eclipse Marketplace Fails

### ISSUE THREAD

**Issue by ChadBae** [Nodeclipse/nodeclipse-1#225]
When i try to install "Gradle IDE Pack 3.8.x+1.0.x", it has a error.  What should I do??

![error](https://user-images.githubusercontent.com/37492738/39281067-bd73223c-493d-11e8-9c58-ff8eb11edc0e.jpg)

**Comment by paulvi** [comment]
Thank you for telling.

This is one more fact for issue #223
