### ISSUE TITLE
Marketplace nodeclipse.github.io problem has occured

### ISSUE THREAD

**Issue by bakseon** [Nodeclipse/nodeclipse-1#230]
A problem has occurred. Please confirm.
eclipse marketplace > Nodeclipse.github.io 1.0.2 >
error "No repository found at https://nodeclipse.github.io."

two computer's version = > eclipse ide 2019-03, jdk 12

**Comment by paulvi** [comment]
OK, checking...

**Comment by paulvi** [comment]
Indeed URL was missing `/updates/`

Changed to `https://nodeclipse.github.io/updates/`

**Comment by bakseon** [comment]
Thank you very much!!!!! have a nice day
