### ISSUE TITLE
Gradle IDE on Marketplace not working

### ISSUE THREAD

**Issue by weric97** [Nodeclipse/nodeclipse-1#231]
I tried to install Gradle IDE from the marketplace as well as going into preferences and changing the update sites. I'm using STS 3.6.4 on Eclipse Luna 4.4.2. Here's a screenshot of the error. 
![image](https://user-images.githubusercontent.com/48689638/59878515-80552b00-9376-11e9-817d-fe2039cb10f9.png)
I understand that this issue has been brought up before but the solution usually resolved by using a different url.

**Comment by paulvi** [comment]
Noted.

Can you try some URLs listed within XML files at
https://github.com/Nodeclipse/nodeclipse.github.io/tree/master/updates/gradle-ide-pack

**Comment by paulvi** [comment]
My guess Pivotal switched to https completely

**Comment by weric97** [comment]
Thanks Paul for the quick response. That did the trick.

**Comment by paulvi** [comment]
Should be OK later on
