### ISSUE TITLE
'Toggle Line Breakpoints' has encountered a problem Resource '/ /index.js.chromium' does not exist.

### ISSUE THREAD

**Issue by pebanfield** [Nodeclipse/nodeclipse-1#48]
Breakpoints are not working in my install. I've tried a fresh mac 64bit eclipse install. I am running OSX version 10.8.3. 

The debugger runs and attaches, but when I try to add a breakpoint to any .chromium version of my source I get the error in the title. 

Does anyone have any ideas of what I could try to resolve the issue? Thanks. 

Peter

**Comment by supamii** [comment]
I ran into this issue and was able to resolve it.

It seemed to have started when I tried to "Push changes to V8 debugger"
I noticed that the debugger fell apart when setting break points on the file that I attempted to sync up with the V8_STANDALONE fileset

"!MESSAGE Resource '/STANDALONE_V8/debug.js (1).chromium' does not exist."

Eventually I tracked down the filecache folder  under org.eclipse.core.filesystem in my workspace .metadata/.plugins path.
